### ISSUE TITLE
Error message while running the app

### ISSUE THREAD

**Issue by Griphcode** [Griphitor/Griph-pad#3]
**Describe the bug**
It gives me a Module not found error message

`
/usr/bin/python3: can't find '__main__' module in '/home/griphcode/Griphitor-Rewrite/.'
`

**Expected behavior**
Opens app without problems

**Screenshots**
![image](https://user-images.githubusercontent.com/83134526/172496539-1b765644-5e08-4124-8933-f76e48992d58.png)

**Desktop (please complete the following information):**
 - OS: [Linux Debian 11]
 - Python Version [2.7.18]

**Comment by Advik-B** [comment]
1. Don't use python2, use python3.9.7
2. Install dependencies before anything:
```
sudo apt update
sudo apt install python3-tk
```
3. git clone it
4. cd to repo
5. cd to src
6. run:
```
python3 .
```

**Comment by Advik-B** [comment]
Also.
# STOP RENAMING THE REPO

**Comment by Advik-B** [comment]
you forgot to cd to src dumass
